version: '3.8'

services:
    db:
      image: 'postgres:15.2'
      container_name: db
      environment:
        - POSTGRES_USER= postgres
        - POSTGRES_PASSWORD= postgres
        - POSTGRES_DB= llm_service
      ports:
        - "5432:15432"  # Assuming you want to use port 8080 locally

    app-api:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      container_name: app-api
      depends_on:
        - db
      ports:
        - "8080:8080"  # Assuming you want to use port 8080 locally
      environment:
        - POSTGRES_USER= postgres
        - POSTGRES_PASSWORD= postgres
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:15432/llm_service
        - SPRING_DATASOURCE_USERNAME= postgres
        - SPRING_DATASOURCE_PASSWORD= postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO= update
